name: Push code to blog.khoah.net S3 bucket

#trigger when push code to master branch
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Deploy-to-S3: #name of the job
    runs-on: ubuntu-latest

    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          mkdir -p ~/.aws   
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/credentials

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      #install Hexo
      - name: Install Hexo
        run: |
          npm install hexo-cli -g 
          npm install 

      #use hexo to enerate files
      - name: Generate files from markdown file using hexo
        run: |
          hexo generate

      #sync the public folder to S3
      - name: Sync public folder to S3 bucket blog.khoah.net
        run: |
          aws s3 sync ./public/ s3://blog.khoah.net
